image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init Flutter
    init: |
      flutter pub get
    command: |
      flutter doctor

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter


