name: ruckup
description: A new Flutter project.

publish_to: 'none' # Remove this if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # ✅ Firebase (Updated to latest stable)
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.7.10

  cloud_functions: ^4.7.6

  # ✅ Auth & File Access
  google_sign_in: ^6.2.1
  file_picker: ^6.1.1
  image_picker: ^1.0.7

  # ✅ UI & Swiping
  flutter_card_swiper: ^4.0.0

  # ✅ GPS Location
  geolocator: ^11.0.0
  geocoding: ^2.2.0

  # ✅ Camera & Permissions
  camera: ^0.10.5+9
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/ruckup_logo.png
    - assets/images/ocp_bg.png
